name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch on which to run the tests
        default: main
        required: true
      sim:
        description: Sim to test - plant-growth, star-navigation
        default: plant-growth
        required: true

jobs:
  test-sim:
    name: Cypress Tests - ${{ github.event.inputs.sim }} sim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
        working-directory: ./
        shell: bash
      - name: Start the application
        run: |
          cd ./
          yarn serve &
        shell: bash
      - name: Install Cypress Dependencies
        run: |
          cd ./tests-e2e
          npm install
        shell: bash
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          wait-on: "http://localhost:8080"
          wait-on-timeout: 300
          # only record the results to dashboard.cypress.io if RECORD_KEY is set
          record: ${{ !!secrets.CYPRESS_RECORD_KEY }}
          working-directory: tests-e2e
          # upload videos for failing specs
          config: video=true,videoUploadOnPasses=false
          spec: cypress/e2e/**/${{ github.event.inputs.sim }}**
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
