name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The git tag for the version to use for index.html
        required: true
env:
  BUCKET: models-resources
  PREFIX: alaskan-simulations
  SRC_FILE: index-top.html
  DEST_FILE: index.html
jobs:
  copy-index-top:
    name: Copy [simulation]/index-top.html
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Add new simulations to this list
          - SIM_FOLDER: "plant-growth"
          - SIM_FOLDER: "star-navigation"
          - SIM_FOLDER: "clam-filtration"
    steps:
      - name: Set S3 Paths
        run: |
          echo "S3_VERSIONED_SIM_PATH=s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/${{ matrix.SIM_FOLDER }}" >> $GITHUB_ENV
          echo "S3_TOP_SIM_PATH=s3://${{ env.BUCKET }}/${{ env.PREFIX }}/${{ matrix.SIM_FOLDER }}" >> $GITHUB_ENV
      # Copy from:
      # models-resources/alaskan-simulations/version/v1.0.0/starter/index-top.html
      # to:
      # models-resources/alaskan-simulations/starter/index.html
      - run: aws s3 cp ${{ env.S3_VERSIONED_SIM_PATH }}/${{ env.SRC_FILE }} ${{ env.S3_TOP_SIM_PATH }}/${{ env.DEST_FILE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
  copy-main-index:
    name: Copy main index.html
    runs-on: ubuntu-latest
    steps:
      # Copy from:
      # models-resources/alaskan-simulations/version/v1.0.0/index.html
      # to:
      # models-resources/alaskan-simulations/index.html
      - run: >
          aws s3 cp
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/version/${{ github.event.inputs.version }}/index.html
          s3://${{ env.BUCKET }}/${{ env.PREFIX }}/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
